# Global Properties
	parchment_mc_version=1.21.5
	parchment_version=2025.04.19
	minecraft_version=1.21.5
	# Check these on https://minecraft.wiki/w/Pack_format
	minecraft_resource_pack_format=55
	minecraft_data_pack_format=71
	modpublisher_version=2.1.6
	shadowjar_version=8.3.6

# Fabric Properties
	# Check these on https://fabricmc.net/develop
	yarn_mappings=1.21.5+build.1
	loader_version=0.16.13

# Fabric Dependencies
	fabric_version=0.121.0+1.21.5
	modmenu_version=14.0.0-rc.2

# Forge Properties
	forge_version=1.21.5-55.0.6
	forge_loader_version_range=[55,)
	forge_version_range=[55,)

# NeoForge Properties - Check https://github.com/neoforged/MDK
	neoforge_version=21.5.49-beta
	neoforge_loader_version_range=[4,)
	neoforge_version_range=[21.5,)

# Common Forge Properties
	minecraft_version_range=[1.21.5, 1.22)