# Global Properties
	parchment_mc_version=1.19.2
	parchment_version=2022.11.27
	minecraft_version=1.19.2
	# Check these on https://minecraft.wiki/w/Pack_format
	minecraft_resource_pack_format=9
	minecraft_data_pack_format=10
	modpublisher_version=2.1.4
	shadowjar_version=8.1.1

# Fabric Properties
	# Check these on https://fabricmc.net/develop
	yarn_mappings=1.19.2+build.28
	loader_version=0.15.11

# Fabric Dependencies
	fabric_version=0.77.0+1.19.2
	modmenu_version=4.2.0-beta.2

# Forge Properties
	forge_version=1.19.2-43.4.0
	forge_loader_version_range=[41,)
	forge_version_range=[41,)

# NeoForge Properties
#	neoforge_version=20.2.88
#	neoforge_loader_version_range=[1,)
#	neoforge_version_range=[20.2,)

# Common Forge Properties
	minecraft_version_range=[1.19, 1.19.2]
