# Global Properties
	parchment_mc_version=1.21.3
	parchment_version=2024.12.07
	minecraft_version=1.21.3
	# Check these on https://minecraft.wiki/w/Pack_format
	minecraft_resource_pack_format=42
	minecraft_data_pack_format=57
	modpublisher_version=2.1.6
	shadowjar_version=8.1.1

# Fabric Properties
	# Check these on https://fabricmc.net/develop
	yarn_mappings=1.21.3+build.2
	loader_version=0.16.9

# Fabric Dependencies
	fabric_version=0.112.1+1.21.3
	modmenu_version=12.0.0

# Forge Properties
	forge_version=1.21.3-53.0.25
	forge_loader_version_range=[53,)
	forge_version_range=[53,)

# NeoForge Properties - Check https://github.com/neoforged/MDK
	neoforge_version=21.3.58
	neoforge_loader_version_range=[4,)
	neoforge_version_range=[21.3,)

# Common Forge Properties
	minecraft_version_range=[1.21.2,1.21.3]