# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false

# Global Properties
	parchment_mc_version=1.20.2
	parchment_version=2023.12.10
	minecraft_version=1.20.2
	# Check these on https://minecraft.wiki/w/Pack_format
	minecraft_resource_pack_format=18
	minecraft_data_pack_format=18
	modpublisher_version=2.1.4
	shadowjar_version=8.1.1

# Fabric Properties
	# Check these on https://fabricmc.net/develop
	fabric_loom_version=1.7-SNAPSHOT
	yarn_mappings=1.20.2+build.4
	loader_version=0.15.11

# Fabric Dependencies
	fabric_version=0.91.6+1.20.2
	modmenu_version=8.0.1

# Forge Properties
	forge_gradle_version=[6.0.24,6.2)
	forge_version=1.20.2-48.1.0
	forge_loader_version_range=[48,)
	forge_version_range=[48,)

# NeoForge Properties
	neoforge_gradle_version=7.0.150
	neoforge_version=20.2.88
	neoforge_loader_version_range=[1,)
	neoforge_version_range=[20.2,)

# Common Forge Properties
	minecraft_version_range=[1.20.2]

# Mod Properties
	mod_id = ichunutil
	mod_name = iChunUtil
	mod_version = 1.0.0
	mod_description = Shared library mod required by most of iChun's Mods.
	maven_group = me.ichun.mods
	archives_base_name = iChunUtil
	mod_license = GNU Lesser General Public License v3.0

# Mod Links
	mod_url_home = https://www.curseforge.com/members/ohaiichun/projects
	mod_url_sources = https://github.com/iChun/iChunUtil
	mod_url_issues = https://github.com/iChun/iChunUtil/issues
	mod_url_discord = https://discord.gg/wvxVkmpt3g

# Publishing Info
	modrinth_project_id=W6ROj0Hl
	curseforge_project_id_forge=229060
	curseforge_project_id_fabric=229060
	curseforge_environment=both