# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false

# Gradle Plugin Versions
	fabric_loom_version=1.7-SNAPSHOT
	forge_gradle_version=[6.0.24,6.2)
	neoforge_gradle_version=7.0.150

# Mod Properties
	mod_id = ichunutil
	mod_name = iChunUtil
	mod_version = 1.0.0
	mod_description = Shared library mod required by most of iChun's Mods.
	maven_group = me.ichun.mods
	archives_base_name = iChunUtil
	mod_license = GNU Lesser General Public License v3.0

# Mod Links
	mod_url_home = https://www.curseforge.com/members/ohaiichun/projects
	mod_url_sources = https://github.com/iChun/iChunUtil
	mod_url_issues = https://github.com/iChun/iChunUtil/issues
	mod_url_discord = https://discord.gg/wvxVkmpt3g

# Publishing Info
	modrinth_project_id=W6ROj0Hl
	curseforge_project_id_forge=229060
	curseforge_project_id_fabric=229060
	curseforge_environment=both