# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false

# Global Properties
	parchment_mc_version=1.21
	parchment_version=2024.06.23
	minecraft_version=1.21
	# Check these on https://minecraft.wiki/w/Pack_format
	minecraft_resource_pack_format=34
	minecraft_data_pack_format=48
	modpublisher_version=2.1.4
	shadowjar_version=8.1.1

# Fabric Properties
	# Check these on https://fabricmc.net/develop
	fabric_loom_version=1.7-SNAPSHOT
	yarn_mappings=1.21+build.2
	loader_version=0.15.11

# Fabric Dependencies
	fabric_version=0.100.3+1.21
	modmenu_version=11.0.1

# Forge Properties
	forge_gradle_version=[6.0.24,6.2)
	forge_version=1.21-51.0.18
	forge_loader_version_range=[51,)
	forge_version_range=[51,)

# NeoForge Properties - Check https://github.com/neoforged/MDK
	neoforge_gradle_version=7.0.150
	neoforge_version=21.0.37-beta
	neoforge_loader_version_range=[4,)
	neoforge_version_range=[21.0,)

# Common Forge Properties
	minecraft_version_range=[1.21,1.22)

# Mod Properties
	mod_id = ichunutil
	mod_name = iChunUtil
	mod_version = 1.0.0
	mod_description = Shared library mod required by most of iChun's Mods.
	maven_group = me.ichun.mods
	archives_base_name = iChunUtil
	mod_license = GNU Lesser General Public License v3.0

# Mod Links
	mod_url_home = https://www.curseforge.com/members/ohaiichun/projects
	mod_url_sources = https://github.com/iChun/iChunUtil
	mod_url_issues = https://github.com/iChun/iChunUtil/issues
	mod_url_discord = https://discord.gg/wvxVkmpt3g

# Publishing Info
	modrinth_project_id=W6ROj0Hl
	curseforge_project_id_forge=229060
	curseforge_project_id_fabric=229060
	curseforge_environment=both